In [1]:
import torch

print(torch.__version__)

2.6.0+cu124


In [3]:
print(torch.cuda.is_available())

False


In [4]:
## create tensor with CPU

import torch

first_tens = torch.tensor([[1,2,3], [11, 12, 13]])

second_tens = torch.tensor([[21,22,23], [31, 32, 33]])

In [5]:
first_tens

tensor([[ 1,  2,  3],
        [11, 12, 13]])

In [6]:
second_tens


tensor([[21, 22, 23],
        [31, 32, 33]])

In [7]:
## add two tensors
add_tensor = first_tens+ second_tens
add_tensor

tensor([[22, 24, 26],
        [42, 44, 46]])

In [9]:
## substrcat two tensors
sub_tensor = second_tens-first_tens
sub_tensor

tensor([[20, 20, 20],
        [20, 20, 20]])

In [10]:
## substrcat two tensors
sub_tensor = first_tens-second_tens
sub_tensor

tensor([[-20, -20, -20],
        [-20, -20, -20]])

In [11]:
## we can move tensors between CPU to GPU
## there may be different ways to create tensors

import torch

import numpy as np

In [14]:
## from the list
tensor_from_list = torch.tensor([1,2,3,4,5])
print("this is list tensor", tensor_from_list)

## from tuple
tensor_from_tuple = torch.tensor((6,7,8,9,10))
print("this is tuple tensor", tensor_from_tuple)

# from array
tensor_from_array = torch.tensor(np.array([11, 12, 14,15]))

print("tensor from array :", tensor_from_array)



this is list tensor tensor([1, 2, 3, 4, 5])
this is tuple tensor tensor([ 6,  7,  8,  9, 10])
tensor from array : tensor([11, 12, 14, 15])


In [15]:
### create different type of tensors
tensor_empty = torch.empty(3,4)
tensor_empty

tensor([[2.1031e-10, 0.0000e+00, 5.3389e-43, 1.6816e-44],
        [2.1031e-10, 0.0000e+00, 1.5512e-42, 0.0000e+00],
        [2.1031e-10, 0.0000e+00, 5.3389e-43, 7.1846e+22]])

In [17]:
tensor_zero = torch.zeros(3,4)
tensor_zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
tensor_one = torch.ones(3,4)
tensor_one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
## tensors with Random values
tensor_rand = torch.rand(3,4)
tensor_rand

tensor([[0.9315, 0.4740, 0.9455, 0.4887],
        [0.5200, 0.3622, 0.4935, 0.8022],
        [0.9270, 0.0057, 0.0545, 0.9697]])

In [21]:
## tensors with Random valueswith normalization   --- important
tensor_rand = torch.randn(3,4)
tensor_rand

tensor([[-0.5241,  0.2832, -0.1867,  0.2344],
        [ 1.1406, -0.2098, -0.3282,  1.0708],
        [-2.7949, -0.1991, -2.0357,  0.7550]])

In [24]:
## tensors with Random values with uniform interger   --- important
tensor_rand = torch.randint(1,10,(2,2)) ## we need to tell the range and size to pick the inter
tensor_rand

tensor([[1, 1],
        [8, 2]])

In [30]:
## like one

tensor_like_one = torch.ones_like(tensor_rand)
tensor_like_one

tensor([[1, 1],
        [1, 1]])

In [31]:
##what are the tensor attributes
## size, rank and data type

In [40]:
import torch

first_tens = torch.tensor([[1,2,3,4,5,5], [2,3,4,5,9,7]])

In [34]:
first_tens.device

device(type='cpu')

In [35]:
first_tens.dtype

torch.int64

In [42]:
first_tens.shape

torch.Size([2, 6])

In [41]:
## dim used for the dimensiins and rank

first_tens.ndim

2

In [55]:
second_tensor = torch.tensor([[1,2,3], [4,5,6],[7,8,9], [10,11,12]]) ## number of brackets decides the ndim
second_tensor

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

In [56]:
second_tensor.dtype

torch.int64

In [57]:
second_tensor.shape

torch.Size([4, 3])

In [58]:
second_tensor.ndim

2

In [59]:
## tensor dtypes
import torch

int_tensor = torch.tensor([1,2,3,4,5], dtype=torch.int8)
int_tensor.dtype

torch.int8

In [60]:
float_tensor = torch.tensor([6,7,8,9],dtype=float)
float_tensor

tensor([6., 7., 8., 9.], dtype=torch.float64)

In [66]:
short_tensor = torch.tensor([6,7,8,9], dtype= torch.int16)
short_tensor.dtype

torch.int16

In [67]:
## casting
int_tensor = int_tensor.float()
int_tensor.dtype

torch.float32

In [68]:
last_tensor = short_tensor.to(dtype=torch.int8)
last_tensor.dtype

torch.int8

In [69]:
## creating tesnors from random samples
import torch

In [70]:
## set the random seed to get fixed values

torch.manual_seed(111)
torch.rand(3,3)

tensor([[0.7156, 0.9140, 0.2819],
        [0.2581, 0.6311, 0.6001],
        [0.9312, 0.2153, 0.6033]])

In [72]:
## lets make a randome normal dist sample
torch.rand(4,4)

tensor([[0.7328, 0.1857, 0.5101, 0.7545],
        [0.2884, 0.5775, 0.0358, 0.1026],
        [0.3419, 0.4400, 0.6341, 0.6224],
        [0.6334, 0.8580, 0.1572, 0.7853]])

In [74]:
## lets set the range
torch.randint(1,20,(3,3))

tensor([[ 3, 19, 10],
        [11, 13, 13],
        [ 3,  5, 10]])

In [75]:
 ## lets make some more zeros

starting_tensor = torch.zeros(2,5)
starting_tensor

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [76]:
## with same size tensors but we random values
torch.manual_seed(111)

rand_tensor = torch.rand_like(starting_tensor)
rand_tensor

tensor([[0.7156, 0.9140, 0.2819, 0.2581, 0.6311],
        [0.6001, 0.9312, 0.2153, 0.6033, 0.7328]])

In [77]:
## with one
torch.ones_like(rand_tensor)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [78]:
## tensor with same number
torch.full_like(starting_tensor, 5)

tensor([[5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.]])

In [79]:
### tensor operations

import torch

In [82]:
one_dim_tensor = torch.tensor([1,2,3,4,5,6,7])
print(one_dim_tensor[2])
print(one_dim_tensor[3].item())

tensor(3)
4


In [83]:
## slicing with tensors
one_dim_tensor[1:4]

tensor([2, 3, 4])

In [85]:
one_dim_tensor[one_dim_tensor>3]

tensor([4, 5, 6, 7])

In [86]:
one_dim_tensor[one_dim_tensor<2]

tensor([1])

In [87]:
first_tensor


tensor([1, 2, 3, 4, 5, 5])

In [90]:
second_tens = torch.tensor([3,4,5,6,7,8])

In [95]:
third = torch.stack((first_tensor, second_tens)) ## same shape k hone chaiye
third

tensor([[1, 2, 3, 4, 5, 5],
        [3, 4, 5, 6, 7, 8]])

In [97]:
## lets split the above tensor
first, second = torch.unbind(third)
first, second

(tensor([1, 2, 3, 4, 5, 5]), tensor([3, 4, 5, 6, 7, 8]))

In [98]:
## based on dimensions
torch.unbind(third, dim=1)

(tensor([1, 3]),
 tensor([2, 4]),
 tensor([3, 5]),
 tensor([4, 6]),
 tensor([5, 7]),
 tensor([5, 8]))

In [103]:
## maths functions

a = torch.tensor([1,2,3,4])
b = torch.tensor([6,7,9,10])
print("addition", a.add(b))
print("subtract", a.subtract(b))
print("Multiply", a.mul(b))
print("Div", a.div(b))

addition tensor([ 7,  9, 12, 14])
subtract tensor([-5, -5, -6, -6])
Multiply tensor([ 6, 14, 27, 40])
Div tensor([0.1667, 0.2857, 0.3333, 0.4000])


In [110]:
## stats. function

stat_tensor = torch.tensor([10,20,30,40,50,60,70,80,90], dtype=float) ## data type error may come if used int

# print("mean", torch.mean(stat_tensor))

In [111]:
stat_tensor

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float64)

In [112]:
torch.mean(stat_tensor)

tensor(50., dtype=torch.float64)

In [113]:
torch.median(stat_tensor
             )

tensor(50., dtype=torch.float64)

In [114]:
torch.mode(stat_tensor)

torch.return_types.mode(
values=tensor(10., dtype=torch.float64),
indices=tensor(0))

In [115]:
torch.std(stat_tensor)

tensor(27.3861, dtype=torch.float64)

In [116]:
### Linear algebra

In [117]:
import torch

In [118]:
first_tensor= torch.tensor([1,2,3])
second_tensor= torch.tensor([4,5,6])

In [121]:
dot_product = torch.matmul(first_tensor, second_tensor)
dot_product ## same goes with 2D or any size

tensor(32)

In [122]:
## eignevalues and eigenvectors

A = torch.randn(4,4)

print("Tell me the matrix A", A)

Tell me the matrix A tensor([[-0.5960, -0.7950, -1.2043, -0.5515],
        [ 0.8237,  0.1488,  0.1024,  0.5572],
        [ 0.2360, -0.8916, -1.1654, -0.6134],
        [-1.0220,  0.2255, -0.4540,  0.7255]])


In [125]:
## get the ## eignevalues and eigenvectors
eignevalues, eigenvectors = torch.linalg.eig(A)
print("eignevalues",eignevalues)
print("eigenvectors", eigenvectors)

eignevalues tensor([ 1.1825+0.0000j, -0.0333+0.0000j, -1.0182+0.8174j, -1.0182-0.8174j])
eigenvectors tensor([[-0.1621+0.0000j, -0.1112+0.0000j,  0.6060+0.0000j,  0.6060-0.0000j],
        [ 0.3032+0.0000j, -0.8219+0.0000j, -0.4080-0.3425j, -0.4080+0.3425j],
        [-0.3582+0.0000j,  0.4327+0.0000j,  0.2955-0.2616j,  0.2955+0.2616j],
        [ 0.8680+0.0000j,  0.3534+0.0000j,  0.4067+0.1668j,  0.4067-0.1668j]])


In [126]:
### Automatic Differentation (Autograd)

import torch

In [132]:
x = torch.autograd.Variable(torch.tensor([2.]), requires_grad=True) ## we need float datatype here else error
y = torch.autograd.Variable(torch.tensor([1.]), requires_grad=True)
z= torch.autograd.Variable(torch.tensor([5.]), requires_grad=True)

In [141]:
## compute gradient
# compute a as difference
a = x-y

# defin a function
f = z*a
f

tensor([5.], grad_fn=<MulBackward0>)

In [142]:
f.backward()

In [143]:
x.grad

tensor([10.])

In [144]:
y.grad

tensor([-10.])

In [145]:
z.grad

tensor([2.])